### PR TITLE
switch to ExtUtils::MakeMaker

### PR DESCRIPTION
**Pull request by mohawk2**
Reasoning: `Module::Build` is no longer recommended or included in the core Perl distro.

Also switches to using `VERSION_FROM` to read from the main module file for the distro version, which aids maintenance and addresses https://rt.cpan.org/Ticket/Display.html?id=81113

### CODE REVIEW

**Comment by timj** [comment]
Grumble grumble (having moved all of my perl modules to Module::Build at one point)...

**Comment by mohawk2** [comment]
Don't hate the player, hate the game! So what do you think?

**Comment by timj** [comment]
Looks fine if that's what we have to do. I'm not entirely sure who's in charge of distributing this module at the moment.

**Comment by mohawk2** [comment]
"Have to" is too strong, but I believe it's the right thing to do. According to PAUSE, you and AALLAN have upload rights (see https://pause.perl.org/pause/authenquery?ACTION=peek_perms). So one way forward is for you to merge this, update the version number to 3.08, then `make dist` and `cpan-upload` (you may need to get and install that).

Alternatively, you could ask AALLAN to add me as a co-maint, but only as a fallback since that's more work for me!

**Comment by mohawk2** [comment]
@timj @aallan Thoughts?

**Comment by mohawk2** [comment]
@timj @aallan No thoughts?

**Comment by mohawk2** [comment]
I'd forgotten I'd already made this PR! @timj your JACH email bounces?

**Comment by mohawk2** [comment]
@grahambell I've rebased this past, and incorporating, your changes.

**Comment by mohawk2** [comment]
@grahambell Seems I missed something, because this was showing with conflicts. I've now rebased again and force-pushed. Thoughts?

**Comment by mohawk2** [comment]
@grahambell If you're not interested, please say so. I've rebased it again, which is necessary with every release because Module::Build is forcing you to update the `Build.PL` each time. EUMM does not need that.

**Comment by mohawk2** [comment]
@grahambell Please can you incorporate this? Tim's original README even refers to MakeMaker.

**Comment by grahambell** [comment]
The README file did indeed seem to contain a mixture of notes about both systems.  It has been updated to be consistent at least.

**Comment by mohawk2** [comment]
@grahambell So you're leaving this dangling? Leaving this using Module::Build is causes extra installations for users of PDL that want to use this module. Are there benefits to using M:B that are subtly hidden somehow?

**Comment by mohawk2** [comment]
RT is not working, and you've turned off GH issues. Nevertheless I want to report this bug so you can ignore that too:

While debugging some FITS stuff in PDL, I added the "-w" flag to the test file. It gave this warning:

```
Negative repeat count does nothing at .../lib/perl5/Astro/FITS/Header/Item.pm line 832.
```

The indicated code is:

```perl
      # Pad goes reverse way to a number
      $value = $value.(' 'x(20-length($value)));
```

The assignment should probably instead be:

```perl
      $value .= ' 'x(20-length($value)) if length($value) < 20;
```

**Comment by timj** [comment]
I'm sorry for your frustration. I'm not supporting any perl packages any more and I am no longer involved in the perl community. This package is supported by one person at the EAO on a best-efforts basis. Do you want to be added as a co-maintainer?

I don't remember turning off GitHub issues but it's possible I did it because RT was meant to be used instead. I no longer have any ability to support this package (and yes, I'm still grumpy that everyone told me to use Module::Build and then after I stopped working with Perl people are complaining that I should be using ExUtils::MakeMaker).

**Comment by mohawk2** [comment]
I understand that grumpiness! I've sweated enough blood over the once and future king (EUMM) ;-)

I'm happy to be co-maint - I'd need collaborator status on this, and co-maint (I'm `ETJ`) on PAUSE.

**Comment by timj** [comment]
I've added you to the GitHub repo. I can't make you a co-main of the PAUSE package because I'm not the owner -- @grahambell is.

**Comment by mohawk2** [comment]
@grahambell Please could you add me as co-maint on PAUSE? Or, if you'd like to hand it off, pass me the "primary permissions" on there?

**Pull request merged**
